### ISSUE TITLE
Feature Request: Add Grapghql response transformer

### ISSUE THREAD

**Issue by rupekeshan** [ComfortablyCoding/strapi-plugin-transformer#52] opened 2022-12-23 09:29 UTC
Since this plugin mainly used to reduce unnessary nested object for api. Need same feature for graphql.

Since graphql return body as string, that transform logic doesn't allowed to transform.

Below code change is to add logic for grapghql.

	if (isAPIRequest(ctx)) {
		const { data } = ctx.body;

		// ensure no error returned.
		if (data) {
			ctx.body['data'] = getPluginService('transformService').response(settings, data);
		}
	}

to

	if (isAPIRequest(ctx)) {
		if(_.isString(ctx.body)){
			ctx.body = JSON.parse(ctx.body);
		}
		const { data } = ctx.body;

		// ensure no error returned.
		if (data) {
			ctx.body['data'] = getPluginService('transformService').response(settings, data);
		}
	}

**Comment by M1CK431** [comment] 2022-12-27 10:59
duplicate of #23

**Comment by M1CK431** [comment] 2022-12-27 11:04
@ComfortablyCoding This feature is requested again and again (with reasons) but since you state in #23 that it's not possible, I suggest to add a note in the README of this project, avoiding people to waste time to try it, figure out it doesn't works with GraphQL, open an issue, you close it...

**Closed** 2022-12-27 21:21 UTC

**Comment by ComfortablyCoding** [comment] 2022-12-27 22:22
Note that GraphQL is not supported has been added to the README

P.S. context #23 & #13

**Comment by M1CK431** [comment] 2022-12-27 23:16
That's great. Thanks 👍🏼
